FROM maven:3.5-jdk-8

WORKDIR /usr/src/app

COPY ./pom.xml ./pom.xml

RUN mvn dependency:go-offline -B

COPY . .

RUN ["mvn", "package"]

EXPOSE 8080

ENTRYPOINT ["java","-jar","target/app-1.0-SNAPSHOT.jar"]
