apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.name }}-secret
type: {{ .Values.mysql.secrets.type }}
data:
  mysql_root_password: {{ .Values.mysql.secrets.data.mysql_root_password | b64enc | quote }}
  mysql_user: {{ .Values.mysql.secrets.data.mysql_user | b64enc | quote }}
  mysql_password: {{ .Values.mysql.secrets.data.mysql_password | b64enc | quote }}
  mysql_database: {{ .Values.mysql.secrets.data.mysql_database | b64enc | quote }}

