
mysql:
  name: mysql
  repository: mysql
  tag: 8
  pullPolicy: IfNotPresent
  replicaCount: 1
  strategy:
    type: Recreate
  service:
    port: 3306
  persistentVolume: mysql-pv
  persistentVolumeClaim: mysql-pvc
  storage:
    className: manual
    capacity: 1Gi
    accessModes: ReadWriteOnce
  pvMountPath: /mnt/data
  mountPath: /var/lib/mysql
  secrets:
    type: Opaque
    data:
      mysql_root_password: root
      mysql_user: root
      mysql_password: 123456
      mysql_database: dev


spring:
  name: spring-rest
  repository: localhost:8083/repository/sonarqube-repo/spring-rest-api
  tag: v1
  pullPolicy: IfNotPresent
  replicaCount: 1
  strategy:
    type: Recreate
  service:
    port: 9090
    targetPort: 8080
    type: NodePort
    


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
